from typing import Protocol, TypeVar

from pydantic import BaseModel

T = TypeVar("T", bound=BaseModel)


class Repository(Protocol[T]):
    def load(self) -> None: ...
    def get(self, pk: str) -> T | None: ...
    def all(self) -> list[T]: ...
    def save(self, entity: T) -> None: ...
    def delete(self, pk: str) -> None: ...
